### ISSUE TITLE
Allow Actor to be initialised

### ISSUE THREAD

**Issue by bsutton** [renatoathaydes/actors#13]
I'm using actors to interact with a db.

When I start each actor I need to do one off initialisation to create a db pool.
When the actor shuts down I need to release the pool.

It would be useful if the Actor had a startup and a shutdown method.

The startup method would be called went the actor is first created (within the new isolate) 
and the shutdown would be called as the actor is closing (again within the isolate).

This would allow the acquisition and cleanup of any expensive resources that can be reused across multiple sends.

Something like:
```dart
var troupe = ActorGroup.of(someMethod)..onStart(startmethod)..onStop(stopmethod);

```
Probably useful if you can pass some args into each as well as pass data from the start method to the stop method.

**Comment by renatoathaydes** [comment]
I considered this idea but found it to be unnecessary because any initialization you might want to do should be done in the constructor..
If I added an `init` method, then it would be possible to have an instance of an actor that's not "ready" to handle messages. We would need to block until the actor was initialized, and that may never happen because `init` could fail. It just introduces more problems than it solves.

Can you give me a link to your code that shows a problem where it's not possible to initialize the actor in the constructor?

**Comment by bsutton** [comment]
The issue is not about constructor initialisation but the need to run startup and shutdown code within the isolate.

I need to create a db connection pool when the isolates starts and shut it down when the isolates finishes.

**Comment by renatoathaydes** [comment]
I think a callback on actor closing should be possible, but can you show me why you can't initialize the connection pool in the constructor?

**Comment by renatoathaydes** [comment]
For the reasons I mentioned above, I did not add an `init` method, only a `close` method to the `Handler` mixin as that was really missing.

For initialization of resources, I would suggest using the following pattern:

```dart
class MyHandler with Handler<int, int> {
  Future<Resource> _resource;

  MyHandler(): _resource = _init();

  @override
  FutureOr<int> handle(int message) async {
    // await for the resource to be ready...
    // react appropriately on errors!
    final resource = await _resource;

    // use resource
    return resource.computeSomething(message);
  }

  @override
  Future<void> close() async {
    // maybe check if the resource initialized properly somehow?
    (await _resource).close();
  }

  Future<Resource> _init() async { TODO() }
}
```

See how there's multiple ways we could react to failures initializing the resource, timeouts, retries etc. which is best left to the application to handle IMO.
