### ISSUE TITLE
Illegal argument in isolate message : (object is a stacktrace)

### ISSUE THREAD

**Issue by synw** [renatoathaydes/actors#5]
I have this message trying to use the library. Here is the code that I run:

```dart
import 'dart:async';
import 'package:actors/actors.dart';

Future<void> processData(
    StreamSink<Map<String, dynamic>> sink, String msg) async {
  sink.add({"message": msg});
  Future.delayed(Duration(seconds: 1));
  sink.add({"end_signal": true});
}

class StreamGenerator with Handler<Data, Stream<Map<String, dynamic>>> {
  @override
  Stream<Map<String, dynamic>> handle(Data data) {
    StreamController<Map<String, dynamic>> controller;
    processData(controller.sink, data.msg);
    return controller.stream;
  }
}

main() async {
  final actor = StreamActor(StreamGenerator());
  final stream = actor.send(Data("my message"));
  await for (final item in stream) {
    if (item.containsKey("message")) {
      print(item["message"]);
    } else if (item.containsKey("end_signal")) {
      print("FINISHED");
    } else {
      throw ("Unknown message");
    }
  }
  await actor.close();
}

class Data {
  Data(this.msg);

  final String msg;
}
```

Traceback:

> Unhandled exception:
> Invalid argument(s): Illegal argument in isolate message : (object is a stacktrace)
> #0      _SendPortImpl._sendInternal (dart:isolate-patch/isolate_patch.dart:219:70)
> #1      _SendPortImpl.send (dart:isolate-patch/isolate_patch.dart:203:5)
> #2      _remote (package:actors/src/actors_base.dart:225:19)
> <asynchronous suspension>
> #3      _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
> #4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
> #5      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
> #6      _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
> #7      _StreamController._add (dart:async/stream_controller.dart:640:7)
> #8      _StreamController.add (dart:async/stream_controller.dart:586:5)
> #9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

**Comment by renatoathaydes** [comment]
You are not initializing the `controller` variable in the `handle` method of `StreamGenerator`.
It should throw an error when you try to use it in the next line:

```dart
StreamController<Map<String, dynamic>> controller;

// controller is null here! This will throw.
processData(controller.sink, data.msg);
```

I need to investigate why you don't just see this error instead of that stracktrace though.

**Comment by synw** [comment]
My bad, sorry. At least we found that the error handling could be improved: it would be good to have to relevant stack trace.

Now I have another problem: the main function does not return I don't know why. Updated code:

```dart
void main() async {
  final actor = StreamActor(StreamGenerator());
  final finished = Completer<Null>();
  StreamSubscription<Map<String, dynamic>> sub;
  sub = actor.send(Data("my message")).listen((Map<String, dynamic> item) {
    switch (item.containsKey("message")) {
      case true:
        print(item["message"]);
        break;
      case false:
        print("FINISHED");
        finished.complete();
    }
  });
  await finished.future;
  print("END");
  await actor.close();
  print("ACTOR CLOSED");
  sub.cancel();
  print("SUBSCRIPTION CANCELED");
}
```
Every line prints but the function does not return, it stays idle.

**Comment by renatoathaydes** [comment]
This is a problem with Isolates.
Unfortunately, you need to call `exit(0)` at the end of the main function.
I couldn't figure out why the Isolates do not all die after we kill them (which we do by closing the actors).
See the code in the example: https://github.com/renatoathaydes/actors/blob/master/example/actors_example.dart#L36

**Comment by synw** [comment]
The isolate must close properly, using exit is not satisfactory: if I use this in a program that does not close immediately the memory leak is a problem. I quickly checked, and it appears that for some reason `kill` is not called

**Comment by renatoathaydes** [comment]
> I quickly checked, and it appears that for some reason kill is not called

How is that possible? The implementation of `close` is this:

```dart
  FutureOr close() async {
    (await isolate).kill(priority: Isolate.immediate);
  }
```

**Comment by synw** [comment]
About the error handling: the last commit throws properly the error: example with the same error as above:

> Unhandled exception:
> NoSuchMethodError: The getter 'sink' was called on null.
> Receiver: null
> Tried calling: sink
> #0      StreamActor.send (package:actors/src/actors_base.dart:167:27)

The message now is correct, if we could have the line number of the original error it would be fine

**Comment by renatoathaydes** [comment]
Strange, I get the line number and file in both Isolates:

```
Unhandled exception:
RemoteErrorException{NoSuchMethodError: The method 'toUpperCase' was called on null.
Receiver: null
Tried calling: toUpperCase()
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      sayHi (file:///home/renato/programming/projects/actors/example/basic_example.dart:5:41)
#2      _HandlerOfFunction.handle (package:actors/src/actors_base.dart:52:36)
#3      _remote (package:actors/src/actors_base.dart:223:33)
<asynchronous suspension>
#4      _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#6      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#7      _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#8      _StreamController._add (dart:async/stream_controller.dart:640:7)
#9      _StreamController.add (dart:async/stream_controller.dart:586:5)
#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
}
#0      Actor.send (package:actors/src/actors_base.dart:146:7)
<asynchronous suspension>
#1      main (file:///home/renato/programming/projects/actors/example/basic_example.dart:10:21)
#2      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#3      main (file:///home/renato/programming/projects/actors/example/basic_example.dart:7:5)
#4      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

**Comment by renatoathaydes** [comment]
>The isolate must close properly, using exit is not satisfactory: if I use this in a program that does not close immediately the memory leak is a problem.

I found the bug! It's almost working now, I just need to fix some edge cases when closing an Actor and there's still messages being processed... will push the fix tomorrow, I hope.

**Comment by synw** [comment]
Great that you found it. About the error handling it's okay there is a line number. As it appears in the middle of the trace it got confused but it's ok now.

**Comment by renatoathaydes** [comment]
The latest commit in the `dev` branch should be working fine now.
I will release on pub after doing some more tests.

**Comment by renatoathaydes** [comment]
The original issue is resolved, so I am closing this ticket. Please create more if you find other problems @synw, thanks!
