### ISSUE TITLE
Incorporate Chain.capture

### ISSUE THREAD

**Issue by modulovalue** [renatoathaydes/actors#7]
Have you heard of Chain.capture @ [stack_trace](https://pub.dev/packages/stack_trace)

The problem that it might solve (unless I'm missing something) is that if an exception were to be thrown inside of a Handler. The most relevant line that is shown in the stacktrace is the actor.send call. I hope Chain.capture could fix that and display the root of the cause (the line that throws the exception inside of the handler)

I was not successful in wrapping the actor and the .send call with a Chain.capture. Is it even possible to do that across isolates? 
If not, could a StackTrace be passed back by a faulty isolate and be chained onto the current isolates StackTrace?

_And thank you for the great library. This is one of those hidden gems that one day probably everybody will have to use in one form or another :)_

**Comment by renatoathaydes** [comment]
This fix has been published on version 0.6.1!
